services:
  web:
    build: .
    container_name: newsarc-web
    ports:
      - "127.0.0.1:4001:4000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start
    volumes:
      - .:/usr/src/app
    networks:
      - infra_network

  consumer:
    build: .
    container_name: newsarc-consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run consumers
    volumes:
      - .:/usr/src/app
    networks:
      - infra_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - infra_network

volumes:
  db_data:

networks:
  infra_network:
    external: true