services:
  web:
    build: .
    container_name: newsarc-web
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=newsarc
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    command: npm run start
    volumes:
      - .:/usr/src/app
  consumer:
    build: .
    container_name: newsarc-consumer
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=newsarc
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    command: npm run consumers
    volumes:
      - .:/usr/src/app
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsarc
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
